question_data = [{"type": "multiple",
                  "difficulty": "medium",
                  "category": "General Knowledge",
                  "question": "Linus Pauling, one of the only winners of multiple Nobel Prizes, earned his Nobel Prizes in Chemistry and what?",
                  "correct_answer": "Peace",
                  "incorrect_answers": ["Physics", "Economics", "Physiology\/Medicine"]},

                 {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                  "question": "Bulls are attracted to the color red.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"type": "multiple", "difficulty": "medium", "category": "General Knowledge",
                  "question": "What was the original name of the search engine &quot;Google&quot;?",
                  "correct_answer": "BackRub",
                  "incorrect_answers": ["CatMassage", "SearchPro", "Netscape Navigator"]},
                 {"type": "multiple", "difficulty": "medium", "category": "General Knowledge",
                  "question": "The term &quot;scientist&quot; was coined in which year?",
                  "correct_answer": "1833", "incorrect_answers": ["1933", "1942", "1796"]},
                 {"type": "multiple", "difficulty": "medium", "category": "General Knowledge",
                  "question": "What is the name given to Indian food cooked over charcoal in a clay oven?",
                  "correct_answer": "Tandoori",
                  "incorrect_answers": ["Biryani", "Pani puri", "Tiki masala"]},
                 {"type": "multiple", "difficulty": "hard", "category": "General Knowledge",
                  "question": "The words &quot;bungalow&quot; and &quot;shampoo&quot; originate from the languages of which country?",
                  "correct_answer": "India",
                  "incorrect_answers": ["Papua New Guinea", "Ethiopia", "China"]},
                 {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                  "question": "A scientific study on peanuts in bars found traces of over 100 unique specimens of urine.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "multiple", "difficulty": "medium", "category": "General Knowledge",
                  "question": "Rolex is a company that specializes in what type of product?",
                  "correct_answer": "Watches",
                  "incorrect_answers": ["Cars", "Computers", "Sports equipment"]},
                 {"type": "multiple", "difficulty": "medium", "category": "General Knowledge",
                  "question": "Which of these is the name of a Japanese system of alternative medicine, literally meaning &quot;finger pressure&quot;?",
                  "correct_answer": "Shiatsu", "incorrect_answers": ["Ukiyo", "Majime", "Ikigai"]},
                 {"type": "multiple", "difficulty": "easy", "category": "General Knowledge",
                  "question": "What was the name of the WWF professional wrestling tag team made up of the wrestlers Ax and Smash?",
                  "correct_answer": "Demolition",
                  "incorrect_answers": ["The Dream Team", "The Bushwhackers",
                                        "The British Bulldogs"]}

                 ]
